cmake_minimum_required (VERSION 2.6)

cmake_policy(SET CMP0011 NEW)

CHECK_CXX_COMPILER_FLAG(-std=c++0x HAVE_STD_CXX0X)



CHECK_CXX_COMPILER_FLAG(-std=c++0x HAVE_STD_CXX0X)
CHECK_CXX_COMPILER_FLAG(-std=c++11 HAVE_STD_CXX11)

IF(HAVE_STD_CXX11)
	CHECK_INCLUDE_FILE_CXX(thread USE_STD_THREAD -std=c++11)
	set(CXX11_FLAG "-std=c++11")
ELSEIF(HAVE_STD_CXX0X)
	CHECK_INCLUDE_FILE_CXX(thread USE_STD_THREAD -std=c++0x)
	set(CXX11_FLAG "-std=c++0x")
ENDIF(HAVE_STD_CXX11)

IF(HAVE_STD_CXX0X OR HAVE_STD_CXX11)
	set(USE_STD_THREAD true)
ELSE(HAVE_STD_CXX0X OR HAVE_STD_CXX11)
	set(USE_STD_THREAD false)
ENDIF(HAVE_STD_CXX0X OR HAVE_STD_CXX11)
